export { default as Map } from 'ol/Map';
export { default as View } from 'ol/View';
export { default as TileLayer } from 'ol/layer/Tile';
export { default as LayerGroup } from 'ol/layer/Group';
export { default as WMTS, optionsFromCapabilities } from 'ol/source/WMTS';
export { default as TileWMS } from 'ol/source/TileWMS';
export { default as WMTSCapabilities } from 'ol/format/WMTSCapabilities';
export { default as ScaleLine } from 'ol/control/ScaleLine';
export * as olProj from 'ol/proj';
export { register } from 'ol/proj/proj4';
export { default as proj4 } from 'proj4';
export { default as LayerSwitcher } from 'ol-layerswitcher';
