export { default as Map } from 'ol/Map';
export { default as View } from 'ol/View';
export { default as Feature } from 'ol/Feature';
export { default as TileLayer } from 'ol/layer/Tile';
export { default as LayerGroup } from 'ol/layer/Group';
export { default as VectorLayer } from 'ol/layer/Vector';
export { default as WMTS, optionsFromCapabilities } from 'ol/source/WMTS';
export { default as TileWMS } from 'ol/source/TileWMS';
export { default as VectorSource } from 'ol/source/Vector';
export { default as OGCMapTile } from 'ol/source/OGCMapTile.js';
export { default as WMTSCapabilities } from 'ol/format/WMTSCapabilities';
export { default as WFS } from 'ol/format/WFS';
export { default as WKT } from 'ol/format/WKT';
export { default as GeoJSON } from 'ol/format/GeoJSON';
export { default as ScaleLine } from 'ol/control/ScaleLine';
export { default as Style } from 'ol/style/Style';
export { default as Stroke } from 'ol/style/Stroke';
export { default as Fill } from 'ol/style/Fill';
export { default as CircleStyle } from 'ol/style/Circle';
export { default as Polygon } from 'ol/geom/Polygon';
export { default as Point } from 'ol/geom/Point';
export * as olLoadingstrategy from 'ol/loadingstrategy';
export * as olProj from 'ol/proj';
export { register } from 'ol/proj/proj4';
export { default as proj4 } from 'proj4';
export { default as LayerSwitcher } from 'ol-layerswitcher';
export { GSearchUI } from '@dataforsyningen/gsearch-ui';
